### ISSUE TITLE
Automate the testing & building with Travis CI

### ISSUE THREAD

**Issue by agentmilindu** [RSVPLK/Dunner#13]
We need to test and build the Dunner everytime a new change is merged to a branch and even the PRs created.

**Comment by ayushjn20** [comment]
Hey @agentmilindu, I am looking over this issue.
I think test files should be added before integration with Travis CI as the default command by Travis CI for Golang projects is `go test -t -v ./... ` and adding go test files highly recommended practice too.

**Comment by vaibhavk** [comment]
@agentmilindu I would like to take this issue, but as @ayushjn20 suggested we need some test to begin with. I'll write few tests to begin with and get TravisCI up and running

**Comment by ayushjn20** [comment]
Hey @vaibhavk , I actually completed my research and I've already started working on it. 
It would be great if you can look for some other issue which is not claimed by anyone. Thanks! :smile:

**Comment by agentmilindu** [comment]
I will create an issue for adding tests

**Comment by ayushjn20** [comment]
Can be closed with reference to #24
