### ISSUE TITLE
Update Developer guide

### ISSUE THREAD

**Issue by shivanshuraj1333** [RSVPLK/Dunner#203]
Since the current master branch is no longer using `dep` as a package manager. 
We need to modify the Developer guide for Installtion of Dunner.

**Comment by shivanshuraj1333** [comment]
Please find the modified wiki page here https://github.com/shivanshu1333/dunner/wiki 
As GitHub [doesn't support pull requests for the wiki repository](https://github.com/gollum/gollum/issues/265) please do the following to modify dunner wiki.
```
git clone https://github.com/leopardslab/dunner.wiki.git
cd dunner.wiki
git pull https://github.com/shivanshu1333/dunner.wiki.git master
git push origin master
```

**Comment by apoorvam** [comment]
@shivanshu1333 I see your changes in Developer Guide, looks good. Is that only change you made? If any other please specify. If there is a way to see the diff, it would be great.

**Comment by shivanshuraj1333** [comment]
@apoorvam Yes, I have modified only the Developer Guide, I think rest of the wiki is good.
You can easily check the diff by various methods, I'm writing one below.
* On en empty folder initialize git repo by cloning the original wiki guide
* Checkout to a temporary branch and git pull modified wiki
* Run `git diff` to see the changes.

Commands for the same:-
`git clone https://github.com/leopardslab/dunner.wiki.git`
`cd dunner.wiki`
`git checkout -b temp`
`git pull https://github.com/shivanshu1333/dunner.wiki.git master --allow-unrelated-histories`
`git diff`

I'm attaching the terminal output of the above commands for reference.
![Screenshot from 2020-02-12 06-24-43](https://user-images.githubusercontent.com/26167974/74293435-d856fc80-4d60-11ea-873e-395c7f39b32f.png)
You can also see the diff in a beautiful manner on vscode after pulling the modified wiki in a temp branch.
![Screenshot from 2020-02-12 06-34-53](https://user-images.githubusercontent.com/26167974/74293843-0b4dc000-4d62-11ea-9cbc-88249eb8b415.png)

**Comment by apoorvam** [comment]
I got it, but i was looking to see diff online without cloning it locally. 

Merged! Thanks for your contribution.
